project:
  type: book
  output-dir: docs

book:
  title: "Health Data Science in Aotearoa New Zealand: A Practical Guide"
  sharing: [twitter, linkedin]
  repo-url: https://github.com/tewhatuora/data-science-guide
  repo-actions: edit
  cover-image: /img/cover.jpg
  date-format: "MMMM YYYY"
  navbar:
    search: true
#    logo: /img/logo-pdh.png
    background: "#005556"
    pinned: true
  sidebar:
#    search: true
    logo: /img/noun-mandatory-1951351.png
    style: floating
    border: true
    tools:
      - icon: github
        href: https://github.com/tewhatuora/data-science-guide
        text: GitHub repository
  chapters:
    - index.qmd
#    - intro.qmd
    - starting.qmd
    - basics.qmd
    - collaboration.qmd
    - data-landscape.qmd
    - data-access.qmd
    - data-identifiability.qmd
    - data-preparation.qmd
    - modelling.qmd
    - evaluation.qmd
    - deployment-lifecycle.qmd
#  comments:
#    hypothesis: true

# banner style for the title
# title-block-banner: "#008084"

# table of contents settings
toc-location: right
toc-title: "On this page"

# captions and references
reference-location: section
cap-location: margin
bibliography: references.bib
csl: csl/archiv-fur-geschichte-der-philosophie.csl
citations-hover: true
citation-location: margin
footnotes-hover: true
# nocite: |
#   @*

# external links
link-external-icon: true
link-external-newwindow: true

format:
  html:
    theme: cosmo

execute:
  freeze: auto
